config/routes.rb
Paperchest::Application.routes.draw do

  root :to => "papers#index"

	get 'tags/:tag', to: 'papers#index', as: :tag
  resources :papers do
    resources :reviews
  end

end

app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :abstract, :citation, :title, :file, :tag_list

  has_many :reviews, :dependent => :destroy

	acts_as_taggable

  has_attached_file :file,
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml"
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :text

  belongs_to :paper
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
#  devise :database_authenticatable, :registerable,
#         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
#  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate


  protected
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == Paperchest::Application.config.auth[:user] && password == Paperchest::Application.config.auth[:password]
    end
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
		if params[:tag]
			@papers = Paper.tagged_with(params[:tag])
		else
    	@papers = Paper.all(order: 'updated_at DESC')
		end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])
    @reviews = @paper.reviews

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
  end

  def create
    @paper = Paper.find(params[:paper_id])
    @review = Review.new(params[:review]) do |r|
      r.paper = @paper
    end

    respond_to do |format|
      if @review.save
        @paper.touch
        format.html { redirect_to @paper, notice: 'Review was successfully created.'}
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    #TODO
  end

  def update
    #TODO
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to paper_path(params[:paper_id])}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperchest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-narrow">
    <div class="masthead">
      <ul class="nav nav-pills pull-right">
        <li class="active">
          <%= link_to "Home" , root_path %>
        </li>
        <li>
          <a href="#">About</a>
        </li>
      </ul>
      <h3 class="muted">Paperchest</h3>
    </div>
    <hr>
    <div class="jumbotron">
      <%= yield %>
    </div>
    <div class="footer">
      mirai CC
    </div>
  </div>
</body>
</html>

app/views/papers/_form.html.erb
<%= form_for @paper, :html => { multipart: true } do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
	<div class="field">
		<%= f.label :tag_list, "Tags (separated by commas)" %>
		<%= f.text_field :tag_list %>
	</div>
  <div class="field">
    <%= f.label :abstract %>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :citation %>
    <%= f.text_area :citation %>
  </div>

  <div class="field">
    <%= f.label 'Paper file' %>
    <%= f.file_field :file %>
  </div>
  <hr>
  <div class="btn-group">
    <%= f.submit class: 'btn btn-small btn-primary' %>
    <% if @paper.id %>
      <%= link_to 'Back', paper_path(@paper), class: 'btn btn-small' %>
    <% else %>
      <%= link_to 'Back', papers_path, class: 'btn btn-small' %>
    <% end %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<h1>Tag cloud</h1>
<div id="tag_cloud">
	<% tag_cloud Paper.tag_counts, %w{t s m l h} do |tag, css_class| %>
		<%= link_to tag.name, tag_path(tag.name), class: css_class %>
	<% end %>
</div>

<hr/>

<h1>Listing papers
	<%= link_to 'New Paper', new_paper_path, class: 'btn btn-success' %>
</h1>


<table class="table table-bordered table-striped">
  <tr>
    <th class="title">Title</th>
    <th>Abstract</th>
		<th>Tags </th>
    <th>Reviews</th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= link_to paper.title, paper %></td>
    <td><%= paper.abstract %></td>
		<td><%= raw paper.tag_list.map { |t| link_to t, tag_path(t) }.join(", ") %> </td>
    <td style="text-align: center"><%= paper.reviews.count %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path, class: 'btn btn-success' %>

app/views/papers/new.html.erb
<h1>Add new paper</h1>

<%= render 'form' %>

app/views/papers/show.html.erb
<% if notice %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times</button>
    <%= notice %>
  </div>
<% end %>

<h2><%= @paper.title %></h2>


<h4>Abstract:</h4>
<p><%= @paper.abstract %></p>

<% unless @paper.citation.empty? %>
  <h4>Citation:</h4>
  <%= simple_format @paper.citation %>
<% end %>

<% unless @paper.tag_list.empty? %>
	<h4>Tags:</h4>
	<p><%= raw @paper.tag_list.map { |t| link_to t, tag_path(t) }.join(", ") %></p>
<% end %>

<div class="btn-group">
  <%= link_to 'Edit', edit_paper_path(@paper), class: 'btn' %>
  <%= link_to 'Destroy', @paper, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %>
  <%= link_to "Read", @paper.file.url(:download => false), :target => '_blank', class: 'btn btn-primary' %>
</div>

<% unless @paper.reviews.empty? %>
  <div class="reviews">
    <%= render template: 'reviews/index' %>
  </div>
  <hr>
<% end %>

<!--
<a href="#modal-review" role='button' class='btn' data-toggle='modal'>Create new review</a>
-->
<%= render template: 'reviews/new' %>
<%= link_to 'Back', papers_path, class: 'btn' %>

app/views/reviews/destroy.js.erb
$('#<%= @review.id %>').slideUp('slow', function(){
  $(this).remove();
});

app/views/reviews/index.html.erb
<h1><small> Reviews </small></h1>
<% @reviews.each do |review| %>
  <div id=<%= review.id %>>
    <div class="row review-item">
      <span class='span8'>
        <%= review.text %>
      </span>
      <span class="span3">
        <div class="btn-group">
          <%= link_to 'Edit', edit_paper_review_path(review.paper, review), class: 'btn btn-info' %>
          <%= link_to 'Destroy', [review.paper, review], remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>
      </span>
    </div>
  </div>
<% end %>

app/views/reviews/new.html.erb
<!-- <div id="modal-review" class="modal hide fade" role='dialog' aria-labelledby='New review' aria-hidden='true'>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="labelModal">Create new review</h3>
  </div>
  <div class="modal-body">
    <%= form_for([@paper, Review.new]) do |f| %>
      <div class="field">
        <%= f.text_area :text %>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <%= f.submit :class => 'btn btn-small' %>
    </div>
  <% end %>
</div> -->

<div id="modal-review">
  <h3 id="labelModal">Create new review</h3>
  <%= form_for([@paper, Review.new]) do |f| %>
    <div class="field">
      <%= f.text_area :text %>
    </div>
    <%= f.submit :class => 'btn btn-success' %>
  <% end %>
</div>